### ISSUE TITLE
populate_data crashes if there is information on the chart

### ISSUE THREAD

**Issue by marimeireles** [QuantStack/xvega#13]
If you have any information added to chart when you try to call `populate_data`, it will cause an error in the notebook:
```
Javascript Error: e is null
```

So if I have this:
```
        /* Creates Chart object */
        xv::Chart chart;

        /* Creates basic xvega template */
        auto json_template = xv::base_vegalite_json();
        populate_data(json_template, chart);
```
My code works.
But if I add `chart.width() = 5;` in between the definition of json_temple and calling populate data, I get the error. Not even sure if it's a bug, but this behavior got me stuck yesterday for a while.

**Comment by madhur-tandon** [comment]
This is strange,

I executed the following snippet:

```
auto chart = Chart();
auto j = base_vegalite_json();

populate_data(j, chart);
std::cout << j.dump(4) << std::endl;
```

I did it in XCode. It works, the output I get is:

```
{
    "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
    "data": {
        "values": [
            {}
        ]
    }
}
```

This is expected. This is because I haven't defined `chart.data` yet, so `values` is empty.

If I insert `chart.width() = 5;` between `auto j = base_vegalite_json();` and `populate_data(j, chart);`, that should work too, but then, the output will still remain the same i.e. the same `json` as above.

This is because `5` is a property of the `chart` object, but the `j` doesn't know about it.

If however you do `j["width"] = chart.width();`, only then you would get the final `json` as:

```
{
    "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
    "data": {
        "values": [
            {}
        ]
    },
    "width": 5.0
}
```

This is exactly what `serialize(json_template, v.width(), "width");` does in `xvega.hpp`

**Comment by madhur-tandon** [comment]
I think that you are doing everything correctly, but the issue is that somehow the whole JSON is null perhaps, you might want to check little things like `pass by value` and `pass by reference` stuff using the `&` operator, etc.

I would do `std::cout << json_template.dump(4) << std::endl;` somewhere on the backend to see the contents of `json_template`

**Comment by madhur-tandon** [comment]
@marimeireles Since the issue is with formatting of the data, Can I close this? Or do we treat it as a separate corner case?

**Comment by marimeireles** [comment]
Thanks @madhur-tandon !
